// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::scheduled_tick_type::ScheduledTick;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProcessTickArgs {
    pub tick: ScheduledTick,
}

impl From<ProcessTickArgs> for super::Reducer {
    fn from(args: ProcessTickArgs) -> Self {
        Self::ProcessTick { tick: args.tick }
    }
}

impl __sdk::InModule for ProcessTickArgs {
    type Module = super::RemoteModule;
}

pub struct ProcessTickCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `process_tick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait process_tick {
    /// Request that the remote module invoke the reducer `process_tick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_process_tick`] callbacks.
    fn process_tick(&self, tick: ScheduledTick) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `process_tick`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ProcessTickCallbackId`] can be passed to [`Self::remove_on_process_tick`]
    /// to cancel the callback.
    fn on_process_tick(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &ScheduledTick) + Send + 'static,
    ) -> ProcessTickCallbackId;
    /// Cancel a callback previously registered by [`Self::on_process_tick`],
    /// causing it not to run in the future.
    fn remove_on_process_tick(&self, callback: ProcessTickCallbackId);
}

impl process_tick for super::RemoteReducers {
    fn process_tick(&self, tick: ScheduledTick) -> __sdk::Result<()> {
        self.imp
            .call_reducer("process_tick", ProcessTickArgs { tick })
    }
    fn on_process_tick(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &ScheduledTick) + Send + 'static,
    ) -> ProcessTickCallbackId {
        ProcessTickCallbackId(self.imp.on_reducer(
            "process_tick",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ProcessTick { tick },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, tick)
            }),
        ))
    }
    fn remove_on_process_tick(&self, callback: ProcessTickCallbackId) {
        self.imp.remove_on_reducer("process_tick", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `process_tick`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_process_tick {
    /// Set the call-reducer flags for the reducer `process_tick` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn process_tick(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_process_tick for super::SetReducerFlags {
    fn process_tick(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("process_tick", flags);
    }
}
